# Generated by Django 4.0.1 on 2022-02-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinalCoder', '0003_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='comentario',
            field=models.CharField(max_length=500),
        ),
    ]
